### ISSUE TITLE
Faulty status update

### ISSUE THREAD

**Issue by ogreid** [Vaggan/com.edling.sectoralarm#1]
A short while after turn on or off the alarm I get two quick faulty status update on Homey. If I turn the alarm off, I get a on and then off within seconds on Homey, or if I turn the alarm on I get a on then off. This can occur somewhere between 15 minutes to a couple of hours after the original change was done.

**Comment by Vaggan** [comment]
I don’t have a solution for your problem right now but I have a new version that I have worked on that might fix the problem. I’m very busy this week but I hope I can release a new version next week or at least a test version.

**Comment by Vaggan** [comment]
You can test this version

https://homey.app/a/com.edling.sectoralarm/test/

**Comment by ogreid** [comment]
Sorry I was not able to test that version

**Comment by Vaggan** [comment]
Have you tried 0.1.1, do you still have the same problem?
