### ISSUE TITLE
Crashing after updating to 0.1.0

### ISSUE THREAD

**Issue by ogreid** [Vaggan/com.edling.sectoralarm#2]
Constantly crashes after upgrading to 0.1.0. Crashes just at few minuttes after app restart

**Comment by ogreid** [comment]
After restarting the app is goes up to about 84MB of memory consumption after 40 sec and then after about 100sec it goes up towards 140MB and then crashes.

**Comment by Vaggan** [comment]
That’s not good!
All I can see in the logs are:
“Invalid login credentials, or account is locked out”
Can you check your credentials and verify that you are not locked out?
When I got locked out I received an email with a link to reactive. 

Even if that should be the problem the memory usage should not be that high. I have to look in to that. 

Maybe try setting the poll interval a bit higher.

**Comment by ogreid** [comment]
Checked my account at Sector and it is not locked

**Comment by Vaggan** [comment]
Have you tried 0.1.1, do you still have the same problem?

**Comment by ogreid** [comment]
Hi I just enabled the app earlier today and so far it is behaving. It has
consumed about 13MB of memory.
I have not added the locks yet

Thanks for the good work

John

tir. 23. mar. 2021 kl. 07:46 skrev Christopher Edling <
***@***.***>:

**Comment by ogreid** [comment]
Just added my two Yale locks. They are both set up to automatically lock
the doors a second after it is closed.
The locks shows up as unlocked in Homey and when I try to toggle the status
I get a red error message saying “Failed to lock the door” but it is
already locked.

John

tir. 23. mar. 2021 kl. 21:09 skrev John Øgreid ***@***.***>:

**Comment by Vaggan** [comment]
Go to the app settings and check the log tab.
Maybe you can see something there or change the drop-down to Full information and see if you get more information next time you get the error.

I do not have a Yale doorman lock myself so it is hard for me to test/develop. I need a lock or someone to test it for me. :)
