### ISSUE TITLE
”Could not find that driver”

### ISSUE THREAD

**Issue by Gurkgurkan** [Vaggan/com.edling.sectoralarm#3]
I am trying to add my controlling unit for Sector Alarm but I keep getting the error message “could not find that driver”.

what could the issue be?

**Comment by Vaggan** [comment]
Unfortunately I can not reproduce the error.
Can you try reinstalling and/or restarting the app?
Can you give a little more information about what you have done, have you filled in your login details?

**Comment by Gurkgurkan** [comment]
Thank you for getting back so quickly! I tried to submit my login info but kept hitting this error
![E5BCFEEA-45E4-4895-871E-436278B8A57B](https://user-images.githubusercontent.com/81194510/112389385-f1b4d100-8cf4-11eb-9cca-e15ca80ee944.png)

So the problem might be that I can not submit my login info?

**Comment by Finnsen** [comment]
I see the exactly same thing. I have the same problem with another app as well. Other apps work fine.

**Comment by Vaggan** [comment]
What other app gives you the same problem? It can help me find the problem.

**Comment by Finnsen** [comment]
Hi.

The "com.scinan.api" shows the same issue. The Developer has not yet replied to my issue ticket.

Ragnar

**Comment by Finnsen** [comment]
The 'sectoralarm' is not installed automatically.

─────────────── Logging stdout & stderr ───────────────
2021-04-07 08:14:05 [log] [MyApp] MyApp is running...
2021-04-07 08:14:05 [err] [ManagerDrivers] Error: Cannot find module 'sectoralarm'
Require stack:
- /drivers/sector_alarm_central/driver.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Util.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Device.js
- /opt/homey-client/node_modules/homey-apps-sdk-v3/index.js
- /opt/homey-client/system/manager/ManagerApps/bootstrap.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:982:15)
    at Function.Module._load (internal/modules/cjs/loader.js:864:27)
    at Module.require (internal/modules/cjs/loader.js:1044:19)
    at Module.homeyRequire [as require] (/opt/homey-client/node_modules/homey-apps-sdk-v3/index.js:11:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/drivers/sector_alarm_central/driver.js:4:21)
    at Module._compile (internal/modules/cjs/loader.js:1158:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1178:10)
    at Module.load (internal/modules/cjs/loader.js:1002:32)
    at Function.Module._load (internal/modules/cjs/loader.js:901:14) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/drivers/sector_alarm_central/driver.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Util.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/lib/Device.js',
    '/opt/homey-client/node_modules/homey-apps-sdk-v3/index.js',
    '/opt/homey-client/system/manager/ManagerApps/bootstrap.js'
  ]
}

**Comment by Finnsen** [comment]
I had to run 'npm install' in the cloned repository. NPM included all the Node Modules in the 'node_modules' folder. I think you should include this in the git repository as Homey does not install them itself. I see other Homey Apps have 'node_modules' folder.

**Comment by Gurkgurkan** [comment]
Hej! Har du hunnit titta mer på detta? Vill verkligen få till Sector alarm i min hemautomation ☺️

**Comment by Vaggan** [comment]
I released a new test version last week. Have you tried it, 0.1.4?
Some people say it works better now. 
https://homey.app/a/com.edling.sectoralarm/test/

**Comment by Finnsen** [comment]
0.1.4 seems to work fine for me so far. I have not made any flows yet, but will try over the next few days.
